version: '3'

services:
  db:
    image: postgres
    container_name: cs545_db_lab04
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: lab04
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres